context("compareRhythms")

load("test_data_ma.rda")

test_that("input validation works", {
  expect_error(compareRhythms(expr, NULL))
  expect_error(compareRhythms(expr, exp_design[-1,]))
  expect_error(compareRhythms(expr, exp_design[,-2]))
  expect_error(compareRhythms(expr, exp_design[,-4]))
  expect_error(compareRhythms(expr, transform(exp_design, time = as.character(time))))
  expect_error(compareRhythms(expr, transform(exp_design, group = as.character(group))))
  expect_error(compareRhythms(expr, within(exp_design, batch <- "a")))
  expect_error(compareRhythms(expr, transform(test, group = factor(group, levels = c(levels(group), "extra")))))
  expect_error(compareRhythms(matrix("a", 10, nrow(exp_design)), exp_design))
  expect_error(compareRhythms(expr, exp_design, method = "test"))
  expect_error(compareRhythms(expr, exp_design, period = 0))
  expect_error(compareRhythms(expr, exp_design, rhythm_fdr = -0.2))
  expect_error(compareRhythms(expr, exp_design, rhythm_fdr = 2))
  expect_error(compareRhythms(expr, exp_design, compare_fdr =  -0.2))
  expect_error(compareRhythms(expr, exp_design, compare_fdr = 2))
  expect_error(compareRhythms(expr, exp_design, amp_cutoff = -0.2))
  expect_error(compareRhythms(expr, exp_design, criterion = "ic"))
  expect_error(compareRhythms(expr, exp_design, schwarz_wt_cutoff = 1.1))
  expect_error(compareRhythms(expr, exp_design, schwarz_wt_cutoff = -0.2))
})
